- name: Check swap is disabled
  fail:
    msg: Kubelet cannot be run with swap enabled
  when: ansible_memory_mb.swap.total > 0

- name: Configure Kubernetes YUM repository
  yum_repository:
    name: kubernetes
    description: kubernetes
    baseurl: "{{ kube_yum_repo_url }}"
    gpgkey: "{{ kube_yum_repo_gpg }}"
    gpgcheck: yes
    repo_gpgcheck: "{{ kube_yum_repo_repo_gpgcheck }}"
- name: Ensure kubelet is installed
  package: name=kubelet-{{ kube_version }} state=present

- name: Create kubelet service override directory
  file: path=/etc/systemd/system/kubelet.service.d state=directory
- name: Configure kubelet service
  template: src=kubelet-override.conf.j2 dest=/etc/systemd/system/kubelet.service.d/override.conf

- name: Ensure kubelet service is running
  service: name=kubelet state=started
- name: Ensure kubelet service is enabled
  service: name=kubelet enabled=yes
